[program:sehat-app-scheduler]
command=/usr/bin/php /var/www/sehat-app/artisan schedule:work
directory=/var/www/sehat-app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/sehat-app/storage/logs/scheduler.log
stopwaitsecs=30

